apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supplychainvisibility-ingress
  namespace: supplychainvisibility
  annotations:
    kubernetes.io/ingress.class: nginx
    networking.gke.io/managed-certificates: "supplychainvisibility-cert"
spec:
  rules:
    - http:
        paths:
          # Path to match /api/config/healthcheck
          - path: /api/config/healthcheck
            pathType: Prefix
            backend:
              service:
                name: configmanagementapi
                port:
                  number: 8000
          # Path for direct healthcheck endpoint
          - path: /api/healthcheck
            pathType: Prefix
            backend:
              service:
                name: configmanagementapi
                port:
                  number: 8000
  # tls:
  #   - hosts:
  #       - gke.staging.golive.settyl.com
  #     secretName: tls-secret
